---
title: "Example 3"
author: "Wei Shi"
date: "03/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, 
                      fig.width = 5, fig.height = 5, dpi = 300,
                      out.width = "90%", fig.align = "center")

library(harrypotter)
library(tidytext)
library(dplyr)
library(tidyr)
library(ggplot2)
library(tibble)

options(tibble.print_max = 10, tibble.print_min = 10)

titles <- c("Philosopher's Stone", "Chamber of Secrets", "Prisoner of Azkaban",
            "Goblet of Fire", "Order of the Phoenix", "Half-Blood Prince",
            "Deathly Hallows")

books <- list(philosophers_stone, chamber_of_secrets, prisoner_of_azkaban,
           goblet_of_fire, order_of_the_phoenix, half_blood_prince,
           deathly_hallows)
  
series <- data_frame()

for(i in seq_along(titles)) {
        
        clean <- data_frame(chapter = seq_along(books[[i]]),
                        text = books[[i]]) %>%
             unnest_tokens(word, text) %>%
             mutate(book = titles[i]) %>%
             select(book, everything())

        series <- rbind(series, clean)
}

# set factor to keep books in order of publication
series$book <- factor(series$book, levels = titles)
```

## Word Clouds

```{r}
library(wordcloud)
library(RColorBrewer)

set.seed(6218)
series %>% 
       anti_join(stop_words) %>%
       count(word) %>%
       with(wordcloud(word, n, max.words = 150, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "PRGn")))
```

## Most Common Positive and Negative words

```{r}
library(reshape2)

series %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("gray20", "gray80"),
                   max.words = 150)
```

